# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Kotlin and Fabric
fabric_api_version=0.155.2+26.1.2
kotlin_version=2.3.0
kotlin_stdlib_version=2.4.0
fabric_language_kotlin_version=1.13.12+kotlin.2.4.0
jsoup_version=1.18.3

# NSM Properties
mod_version=1.0.2
maven_group=com.nico
archives_base_name=NicosSuperMods

# Mod Dependency Properties
yacl_version=3.8.2+1.21.11-fabric
modmenu_version=18.0.0
moulconfig_version=modern-26.1:4.7.2
odin_version=0.3.0